name: opengraph
domain: wayl.one
port: 8000
image:
  repository: registry.wayl.one
  name: opengraph
  tag: "0.0.1"
imageTag: 0.0.1
imagePullSecret: cluster-regcred
minReplicas: 1
maxReplicas: 3
targetCPUUtilization: 800
cpuRequest: 50m
cpuLimit: 500m
memoryRequest: 100Mi
memoryLimit: 500Mi
targetMemoryUtilization: 400

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10000
  fsGroup: 10000

containerSecurityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true

probes:
  liveness:
    path: /health
    initialDelaySeconds: 15
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 3
    successThreshold: 1
  readiness:
    path: /ready
    initialDelaySeconds: 5
    periodSeconds: 10
    timeoutSeconds: 3
    failureThreshold: 3
    successThreshold: 1

nodeSelector: {}
tolerations: []
affinity: {}