name: opengraph
domain: wayl.one
port: 8000
image:
  repository: registry.wayl.one
  name: opengraph
  tag: "0.0.1"
imageTag: 0.0.1
imagePullSecret: cluster-regcred
minReplicas: 1
maxReplicas: 3
targetCPUUtilization: 800
cpuRequest: 50m
cpuLimit: 500m
memoryRequest: 100Mi
memoryLimit: 500Mi
targetMemoryUtilization: 400
