apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: {{ .Values.name }}
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace | default .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      service: {{ .Values.name }}
  template:
    metadata:
      labels:
        service: {{ .Values.name }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}/{{ .Values.name }}:{{ .Values.image.tag }}
          name: {{ .Values.name }}
          ports:
            - containerPort: {{ .Values.port }}
              protocol: TCP
          resources:
            requests:
              cpu: {{ .Values.cpuRequest }}
              memory: {{ .Values.memoryRequest }}
            limits:
              cpu: {{ .Values.cpuLimit }}
              memory: {{ .Values.memoryLimit }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecret }}
